"""Sinh bảng gom nhóm MCC -> nhóm chi phí: data/mcc_groups.csv.

Thứ tự áp dụng: danh sách tường minh (EXPLICIT) trước, sau đó mới đến quy tắc theo từ khóa
cho tên thương hiệu (hãng bay, khách sạn, hãng thuê xe). Làm vậy để tránh bắt nhầm,
ví dụ 'AUTOMOTIVE REPAIR' chứa chữ 'AIR'.

Chạy: .venv/Scripts/python scripts/build_mcc_groups.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.data_loader import load_pcard  # noqa: E402
from src.labels import GROUPS  # noqa: E402

EXPLICIT = {
    'AIR_TRAVEL': [
        'AIRLINES  AIR CARRIERS', 'TRAVEL AGENCIES', 'AIRPORTS  FLYING FIELDS  AIRPORT TERMINA',
        'DELTA', 'IBERIA', 'KLM', 'LUFTHANSA', 'SWISS', 'AVIANCA', 'AEROMEXICO', 'AER LINGUS',
        'FINNAIR', 'WESTJETAIR', 'RYANAIR', 'EASYJET AIR', 'ICELANDAIR', 'BAHAMASAIR',
        'CATHAY PACIFIC', 'AIRMARO', 'QANTAS AIR', 'EVA AIRLINES', 'VIRGIN ATLANTIC', 'AEROLINEAS ARGENTINAS',
    ],
    'LODGING': [
        'LODGING  HOTELS  MOTELS  RESORTS', 'TRAILER PARKS AND CAMPGROUNDS',
        'HILTON', 'HILTON INTERNATIONAL', 'HILTON CONRAD', 'MARRIOTT', 'HYATT HOTELS', 'HYATT PLACE', 'AMERICINN', 'WESTIN', 'SHERATON',
        'WYNDHAM', 'DOUBLETREE', 'ALOFT', 'ELEMENT', 'CANOPY', 'CURIO HOTELS', 'TRIBUTE PORTFOLIO',
        'WALDORF', 'W HOTELS', 'BELLAGIO', 'GOLDEN NUGGET', 'GREAT WOLF', 'RADISSON', 'RADISSON BLU',
        'EXTENDED STAY', 'EXTENDED STAY AMERICA', 'TRAVELODGE', 'ECONOLODGES', 'HOWARD JOHNSON',
        'SONESTA HOTELS', 'LOEWS HOTELS', 'OMNI HOTELS', 'SWISSOTEL', 'MERIDIEN HOTELS', 'SOFITEL HOTELS',
        'FAIRMONT HOTELS CORP.', 'SHANGRI-LA INTERNATIONAL', 'FOUR SEASONS HOTELS', 'THE RITZ-CARLTON',
        'COSMOPOLITAN OF LAS VEGAS', 'FLAMINGO HOTELS', 'PARIS LAS VEGAS HOTEL', 'MANDALAY BAY RESORT',
        'FONTAINEBLEAU RESORTS', 'DISNEY RESORTS', 'GAYLORD OPRYLAND', 'GAYLORD PALMS', 'MGM GRAND HOTEL',
        'OUTRIGGER HOTELS AND RESORTS', 'HAWTHORNE BY WYNDHAM', 'HOTELS MELIA', 'SCANDIC HOTELS',
        'PRINCE HOTELS', 'MAINSTAY SUITES', 'DOLCE HOTELS AND RESORTS',
    ],
    'GROUND_TRANSPORT': [
        'TAXICABS/LIMOUSINES', 'AUTOMOBILE PARKING LOTS AND GARAGES', 'TOLLS  ROAD AND BRIDGE FEES',
        'BUS LINES  CHARTERS  TOUR BUSES', 'PASSENGER RAILWAYS', 'LOCAL SUBURBAN COMMUTER PASSENGER TRANSP',
        'TRANSPORTATION SERVICES NOT ELSEWHERE CL', 'STEAMSHIP/CRUISE LINES', 'CAR RENTAL AGENCIES NOT ELSEWHERE CLASSI',
        'ENTERPRISE RENT-A-CAR', 'NATIONAL CAR RENTAL', 'HERTZ CORPORATION', 'AVIS RENT-A-CAR',
        'BUDGET RENT-A-CAR', 'ALAMO RENT-A-CAR', 'DOLLAR RENT-A-CAR', 'SIXT CAR RENTAL', 'PAYLESS CAR RENTAL',
        'MOTOR HOME AND RECREATIONAL VEHICLE RENT', 'BOAT RENTALS AND LEASE', 'TRUCK AND UTILITY TRAILER RENTAL',
    ],
    'FOOD': [
        'EATING PLACES  RESTAURANTS', 'FAST FOOD RESTAURANTS', 'CATERERS', 'BAKERIES',
        'DRINKING PLACES (ALCOHOLIC BEV.)-BARS TA', 'GROCERY STORES  SUPERMARKETS',
        'MISC FOOD STORES-SPECIALITY CONVENIENCE', 'FREEZER AND LOCKER MEAT PROVISIONERS',
        'DAIRY PRODUCTS STORES', 'CANDY  NUT CONFECTIONERY STORES',
    ],
    'OFFICE_PRINT': [
        'BOOK STORES', 'STATIONERY OFFICE SUPPLIES PRINTING AND', 'STATIONARY  OFFICE AND SCHOOL SUPPLY STO',
        'MISCELLANEOUS PUBLISHING & PRINTING', 'QUICK-COPY AND REPRODUCTION SERVICES',
        'OFFICE  PHOTOGRAPHIC  PHOTOCOPY  AND MIC', 'BOOKS PERIODICALS AND NEWSPAPERS', 'NEWS DEALERS AND NEWSSTANDS',
        'POSTAGE STAMPS', 'TYPESETTING PLATE MAKING & RELATED SERVI', 'ARTIST SUPPLY STORES  CRAFT SHOPS',
        'DIGITAL GOODS - MEDIA BOOKS MOVIES MUSIC',
    ],
    'IT_TELECOM': [
        'COMPUTER SOFTWARE STORES', 'COMPUTER AND DATA PROCESSING SERVICES', 'COMPUTER NETWORK/INFORMATION SERVICES',
        'COMPUTERS COMPUTER PERIPHERAL EQUIPMENT', 'COMPUTER MAINTENANCE REPAIR & SERVICES N', 'ELECTRONIC SALES',
        'LARGE DIGITAL GOODS MERCHANT', 'DIGITAL GOODS - APPS (EXCLUDES GAMES)', 'DIGITAL GOODS - GAMES',
        'INFORMATION RETRIEVAL SERVICES', 'TELECOMMUNICATION SERV.INCLUD. LOCAL/L.D',
        'TELECOMMUNICATION EQUIPMENT INCLUDING TE', 'CABLE  SATELLITE & OTHER PAY TV/RADIO SE',
        'CONTINUITY/SUBSCRIPTION MERCHANTS', 'CAMERA AND PHOTOGRAPHIC SUPPLY STORES',
        'RADIO  TELEVISION AND STEREO REPAIR SHOP',
    ],
    'MEDICAL_LAB': [
        'LAB/MEDICAL/DENTAL/OPHTHALMIC HOSPITAL E', 'MEDICAL AND DENTAL LABORATORIES', 'TESTING LABORATORIES (NON-MEDICAL)',
        'CHEMICALS AND ALLIED PRODUCTS NOT ESLEWH', 'DRUG STORES  PHARMACIES', 'DRUGS DRUG PROPRIETARIES AND DRUGGIST S',
        'MEDICAL SERVICES & HEALTH PRACTITIONERS', 'DOCTORS  PHYSICIANS', 'HOSPITALS', 'DENTISTS  ORTHODONTISTS',
        'OPTOMETRISTS  OPTHAMOLOGISTS', 'OPTICIANS', 'CHIROPRACTORS', 'HEARING AID SALES  SERVICE  SUPPLY STORE',
        'ORTHOPEDIC GOODS-ARTIFICIAL LIMB STORES', 'AMBULANCE SERVICES', 'NURSING AND PERSONAL CARE FACILITIES',
    ],
    'FACILITIES_MRO': [
        'INDUSTRIAL SUPPLIES NOT ESLEWHERE CLASSI', 'HOME SUPPLY WAREHOUSE STORES', 'HARDWARE STORES',
        'HARDWARE EQUIPMENT AND SUPPLIES', 'PLUMBING & HEATING EQUIPMENT AND SUPPLIE', 'ELECTRICAL PARTS AND EQUIPMENT',
        'CONSTRUCTION MATERIALS', 'LUMBER AND BUILDING MATERIALS STORES', 'GLASS  PAINT  WALLPAPER STORES',
        'PAINTS VARNISHES AND SUPPLIES', 'METAL SERVICE CENTERS AND OFFICES', 'COMMERCIAL EQUIPMENT  NOT ELSEWHERE CLAS',
        'DURABLE GOODS NOT ELSEWHERE CLASSIFIED', 'EQUIP RENTALS & LEASING SERVICES  TOOL R',
        'HEATING  PLUMBING  AIR CONDITIONING CONT', 'SPECIAL TRADE CONTRACTORS', 'GENERAL CONTRACTORS-RESIDENTIAL',
        'ELECTRICAL CONTRACTORS', 'CONTRACTORS  CONCRETE WORK', 'ROOFING & SIDING  SHEET METAL WORK',
        'MASONRY STONEWORK TILE SETTING PLASTERIN', 'CARPENTRY', 'WELDING', 'AIR CONDITIONING AND REFRIGERATION REPAI',
        'FURNITURE  HOME FURNISHINGS AND EQUIPMEN', 'COMMERCIAL FURNITURE', 'MISCELLANEOUS HOUSE FURNISHING SPECIALIT',
        'FLOOR COVERING  RUG AND CARPET STORES', 'WINDOW COVERING  UPHOLSTERY AND DRAPERY',
        'FIREPLACE  FIREPLACE SCREENS  AND ACCESS', 'HOUSEHOLD APPLIANCE STORES', 'SWIMMING POOLS-SALES AND SUPPLIES',
        'TENT AND AWNING SHOPS', 'DISINFECTING AND EXTERMINATING SERVICES', 'CLEANING AND MAINTENANCE  JANITORIAL SER',
        'SPECIALITY CLEANING POLISHING & SANITATI', 'CARPET AND UPHOLSTERY CLEANING',
        'MISCELLANEOUS REPAIR SHOPS AND RELATED S', 'ELECTRICAL AND SMALL APPLIANCE REPAIR SH',
        'REUPHOLSTERY AND FURNITURE REPAIR  FURNI', 'WRECKING AND SALVAGE YARDS',
    ],
    'VEHICLE_FUEL': [
        'AUTOMOTIVE PARTS  ACCESSORIES STORES', 'MISCELLANEOUS AUTOMOTIVE DEALERS', 'SERVICE STATIONS',
        'AUTOMATED FUEL DISPENSERS', 'AUTO AND TRUCK DEALERS-(NEW&USED)-SALES', 'AUTOMOBILE AND TRUCK DEALERS- (USED ONLY',
        'AUTOMOTIVE REPAIR SHOPS (NON-DEALER)', 'AUTOMOTIVE TIRE STORES', 'TIRE RETREADING AND REPAIR SHOPS',
        'FUEL DEALERS-FUEL OIL  WOOD  COAL  LIQUE', 'PETROLEUM AND PETROLEUM PRODUCTS', 'MOTOR VEHICLE SUPPLIES AND NEW PARTS',
        'RECREATIONAL AND UTILITY TRAILER  CAMPER', 'MOTORCYCLE DEALERS', 'MARINAS  MARINE SERVICE/SUPPLIES',
        'BOAT DEALERS', 'CAR WASHES', 'AUTOMOTIVE BODY REPAIR SHOPS', 'AUTOMOTIVE PAINT SHOPS', 'TOWING SERVICES',
        'ELECTRIC VEHICLE CHARGING', 'AUTOMOBILE ASSOCIATIONS', 'MOBILE HOME DEALERS',
    ],
    'UTILITIES': [
        'UTILITIES-ELEC/GAS/HEAT OIL/SANITARY/WTR',
    ],
    'PROF_SERVICES': [
        'BUSINESS SERVICES NOT ELSEWHERE CLASSIFI', 'COURIER SERVICES-AIR OR GROUND FREIGHT F', 'ADVERTISING SERVICES',
        'PROFESSIONAL SERVICES NOT ELSEWHERE CLAS', 'MANAGEMENT  CONSULTING AND PUBLIC RELATI',
        'EMPLOYMENT AGENCIES  TEMPORARY HELP SUPP', 'DETECTIVE AGENCIES & PROTECTIVE AGENCY A',
        'COMMERCIAL PHOTOGRAPHY  ART  AND GRAPHIC', 'PHOTOGRAPHIC STUDIOS', 'PHOTOFINISHING LABORATORIES  PHOTO DEVEL',
        'STENOGRAPHIC SERVICES', 'LEGAL SERVICES  ATTORNEYS', 'ACCOUNTING  AUDITING AND BOOKKEEPING SER',
        'ENGINEERING  ARCHITECTURAL AND SURVEYING', 'INSURANCE-SALES & UNDERWRITING', 'DIRECT MARKETING INSURANCE SERVICES',
        'REAL ESTATE AGENTS AND MANAGERS-RENTALS', 'MOTION PICTURE & VIDEO TAPE PRODUCTION &',
        'MOTOR FREIGHT CARRIERS  TRUCK-LOCAL/LONG', 'RAILROADS - FREIGHT',
        'LAUNDRIES SERVICES-FAMILY AND COMMERCIAL', 'DRY CLEANERS', 'LAUNDRY  CLEANING  AND GARMENT SERVICES',
        'TAX PREPARATION SERVICE', 'MISCELLANEOUS PERSONAL SERVICES',
    ],
    'FEES_EDU_EVENTS': [
        'GOVERNMENT SERVICES NOT ELSEWHERE CLASSI', 'TAX PAYMENTS', 'COURT COSTS INCLUDING ALIMONY AND CHILD', 'FINES',
        'OTHER FEES', 'CHARITABLE AND SOCIAL SERVICE ORGANIZATI', 'MEMBERSHIP ORGANIZATIONS NOT ELSEWHERE C',
        'CIVIC  SOCIAL AND FRATERNAL ASSOCIATIONS', 'RELIGIOUS ORGANIZATIONS', 'POLITICAL ORGANIZATIONS',
        'SCHOOLS AND EDUCATIONAL SERVICES NOT ELS', 'COLLEGES  UNIVERSITIES  PROFESSIONAL SCH', 'VOCATIONAL AND TRADE SCHOOLS',
        'BUSINESS AND SECRETARIAL SCHOOLS', 'ELEMENTARY AND SECONDARY SCHOOLS', 'CORRESPONDENCE SCHOOLS',
        'DANCE HALLS  STUDIOS  AND SCHOOLS', 'CHILD CARE SERVICES', 'MEMBERSHIP CLUBS (SPORTS RECREATION ATHL',
        'COMM. SPORTS  PROF. SPORTS CLUBS ATHLETI', 'SPORTING AND RECREATIONAL CAMPS',
        'AMUSEMENT RECREATION SERVICES (SWIMMING', 'TOURIST ATTRACTIONS AND EXHIBITS',
        'THEATRICAL PRODUCERS (EXCEPT MOTION PICT', 'BANDS  ORCHESTRAS  ENTERTAINERS', 'MOTION PICTURE THEATERS',
        'AMUSEMENT PARKS  CIRCUSES  CARNIVALS  FO', 'AQUARIUMS  SEAQUARIUMS AND DOLPHINARIUMS', 'GOLF COURSES-PUBLIC',
        'BOWLING ALLEYS', 'VIDEO GAME ARCADES/ESTABLISHMENTS', 'BILLIARD AND POOL ESTABLISHMENTS',
    ],
    'APPAREL_SPORTS': [
        'MEN S WOMENS AND CHILDREN S UNIFORMS AND', 'MEN S AND WOMEN S CLOTHING STORES', 'SHOE STORES',
        'MISCELLENEOUS APPAREL AND ACCESSORY STOR', 'SPORTS APPAREL  RIDING APPAREL STORES', 'FAMILY CLOTHING STORES',
        'WOMEN S ACCESSORY AND SPECIALITY SHOPS', 'WOMEN S READY TO WEAR STORES', 'MEN S AND BOYS  CLOTHING AND ACCESSORIES',
        'CHILDREN S AND INFANT S WEAR STORES', 'COMMERCIAL FOOTWEAR', 'CLOTHING RENTAL-COSTUMES/UNIFORMS',
        'TAILORS  SEAMSTRESS  MENDING  ALTERATION', 'SHOE REPAIR SHOPS  SHOE SHINE PARLORS &', 'SPORTING GOODS STORES',
        'BICYCLE SHOPS-SALES AND SERVICE', 'SEWING  NEEDLEWORK  FABRIC AND PIECE GOO', 'PIECE GOOD NOTIONS AND OTHER DRY GOODS',
    ],
    'AGRI_ANIMAL': [
        'AGRICULTURAL COOPERATIVES', 'NURSERIES  LAWN AND GARDEN SUPPLY STORES', 'FLORISTS SUPPLIES NURSERY STOCK & FLOWER',
        'LANDSCAPE AND HORTICULTURAL SERVICES', 'PUBLIC WAREHOUSING-FARM PROD REFRIDGERAT', 'PET SHOPS-PET FOOD AND SUPPLY STORES',
        'VETERINARY SERVICES',
    ],
    'RETAIL_GENERAL': [
        'MISCELLANEOUS AND RETAIL STORES', 'VARIETY STORES', 'MISCELLANEOUS GENERAL MERCHANDISE STORES', 'DISCOUNT STORES',
        'DEPARTMENT STORES', 'CATALOG MERCHANTS', 'ALL OTHER DIRECT MARKETERS', 'COMBINATION CATALOG AND RETAIL MERCHANT',
        'WHOLESALE CLUBS', 'MARKETPLACES', 'NON-DURABLE GOODS NOT ELSEWHERE CLASSIFI', 'USED MERCHANDISE STORES  SECOND HAND STO',
        'DUTY FREE STORES', 'HOBBY TOY  AND GAME SHOPS', 'MUSIC STORES-MUSICAL INSTRUMENTS  PIANOS',
    ],
    'OTHER': [
        'PACKAGE STORES  BEER  LIQUOR', 'CIGAR STORES AND STANDS', 'JEWELRY STORES-WATCHES  CLOCKES  AND SIL',
        'PRECIOUS STONES AND METALS  WATCHES & JE', 'WATCH  CLOCK AND JEWELRY REPAIR', 'MASSAGE PARLORS',
        'HEALTH AND BEAUTY SPAS', 'BEAUTY SHOPS AND BARBER SHOPS', 'COSMETIC STORES', 'FLORISTS',
        'GIFT  CARD  NOVELTY  AND SOUVENIR SHOPS', 'ANTIQUE SHOPS', 'ANTIQUE REPRODUCTION STORES', 'ART DEALERS AND GALLERIES',
        'STAMP & COIN STORES-PHILATELIC & NUMISMA', 'RELIGIOUS GOODS STORES', 'FURRIERS AND FUR SHOPS',
        'FUNERAL SERVICE AND CREMATORIES', 'POI FUNDING TRANSACTIONS EXCLUDING MONEYSEND', 'WIRE TRANSFER MONEY ORDERS',
        'AUTOGRAPH', 'VIDEO RENTAL STORES', 'VIDEO AMUSEMENT GAME SUPPLIES', 'LUGGAGE AND LEATHER GOODS STORES',
        'RECORD SHOPS', 'GLASSWARE AND CRYSTAL STORES', 'PAWN SHOPS',
    ],
}

# Chỉ áp dụng cho MCC chưa có trong EXPLICIT (tên thương hiệu).
PATTERNS = [
    ('AIR_TRAVEL', r'AIRLINE|AIRWAYS|\bAIR\b|^AIR |AIR CAN|SCANDINAVIAN AIRLINE'),
    ('LODGING', r'HOTEL|\bINNS?\b|SUITES|RESORT|MOTEL|CASINO|LODG|PLAZA'),
]


def assign(mcc: str) -> str | None:
    for group, names in EXPLICIT.items():
        if mcc in names:
            return group
    for group, pattern in PATTERNS:
        if re.search(pattern, mcc):
            return group
    return None


def main():
    dupes = [m for g, ms in EXPLICIT.items() for m in ms if sum(m in v for v in EXPLICIT.values()) > 1]
    assert not dupes, f'MCC nằm ở nhiều nhóm: {set(dupes)}'
    unknown_groups = set(EXPLICIT) - set(GROUPS)
    assert not unknown_groups, unknown_groups

    counts = load_pcard().mcc_desc.value_counts()
    table = counts.rename('n_rows').rename_axis('mcc_desc').reset_index()
    table['group_code'] = table.mcc_desc.map(assign)

    missing = table[table.group_code.isna()]
    if len(missing):
        print('CHƯA GOM ĐƯỢC:\n', missing.to_string())
        sys.exit(1)
    stale = [m for ms in EXPLICIT.values() for m in ms if m not in counts.index]
    if stale:
        print('Cảnh báo – MCC trong EXPLICIT không có trong dữ liệu:', stale)

    table['group_name'] = table.group_code.map(GROUPS)
    order = {g: i for i, g in enumerate(GROUPS)}
    table = table.sort_values(['group_code', 'n_rows'], key=lambda s: s.map(order) if s.name == 'group_code' else -s)
    out = ROOT / 'data' / 'mcc_groups.csv'
    table[['group_code', 'group_name', 'mcc_desc', 'n_rows']].to_csv(out, index=False, encoding='utf-8-sig')
    print(f'Đã ghi {len(table)} MCC -> {out}')


if __name__ == '__main__':
    main()
